version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - 8080:8080
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - 80:3000
    env_file:
      - ./frontend/booker-frontend/.env
  db:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - pgbooker:/var/lib/postgresql/data
      - ./data/dump.sql:/docker-entrypoint-initdb.d/dump.sql

volumes:
  pgbooker:
